#!/bin/bash
# Quick Start Guide for MiniPupper Bluetooth Interface

echo "=========================================="
echo "MiniPupper Bluetooth Interface Setup"
echo "=========================================="
echo ""

# Make scripts executable
echo "Making scripts executable..."
chmod +x run_robot_bluetooth.py
chmod +x serve_web_joystick.py

echo "✓ Scripts are now executable"
echo ""
echo "=========================================="
echo "Usage Options:"
echo "=========================================="
echo ""
echo "Option 1: Web Joystick Control"
echo "-------------------------------"
echo "1. Start the robot with Bluetooth:"
echo "   ./run_robot_bluetooth.py"
echo ""
echo "2. In another terminal, start the web server:"
echo "   ./serve_web_joystick.py"
echo ""
echo "3. On your mobile device:"
echo "   - Connect to same WiFi"
echo "   - Open browser to the URL shown"
echo "   - Click 'Connect via Bluetooth'"
echo "   - Control with virtual joysticks!"
echo ""
echo "Option 2: MCP Block Programming"
echo "--------------------------------"
echo "1. Start the robot with Bluetooth:"
echo "   ./run_robot_bluetooth.py"
echo ""
echo "2. Connect your block programming tool"
echo "   (e.g., Block-Xiaozhi, Claude) to:"
echo "   Service UUID: 0d9be2a0-4757-43d9-83df-704ae274b8df"
echo ""
echo "3. Use MCP tools to control robot:"
echo "   - move_forward(time=2.0)"
echo "   - turn_left(time=1.0)"
echo "   - look_up(time=1.0)"
echo "   - hop()"
echo "   - etc."
echo ""
echo "=========================================="
echo "Additional Commands:"
echo "=========================================="
echo ""
echo "Run with IMU support:"
echo "  ./run_robot_bluetooth.py --use-imu"
echo ""
echo "Test without BLE (demo mode):"
echo "  ./run_robot_bluetooth.py --no-ble"
echo ""
echo "=========================================="
echo ""
echo "For detailed documentation, see:"
echo "  BLUETOOTH_README.md"
echo ""
echo "Ready to go! 🐕"
echo ""
