#!/bin/bash

#
# Copyright (c) 2021, Mangdang Technology Co., Limited
#


IO_MAP=(
12 0
13 0
16 0
)

function io_init(){
	len=${#IO_MAP[@]}
	for((i=0;i<len;i+=2))
	do
		io=${IO_MAP[i]}
		val=${IO_MAP[i+1]}
		echo $io > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio$io/direction
		echo $val > /sys/class/gpio/gpio$io/value
	done
}

#Init IO about
io_init

#Load max17205 driver
sudo insmod /lib/modules/`uname -r`/kernel/drivers/power/supply/max1720x_battery.ko
sleep 1

#Power monitor
while true
do
	current_voltage=`cat /sys/class/power_supply/max1720x_battery/voltage_now`
	if [ $current_voltage -le 63000 ]; then
		echo 1 > /sys/class/gpio/gpio16/value
		echo 0 > /sys/class/gpio/gpio12/value
		echo 1 > /sys/class/gpio/gpio13/value
	else
		echo 0 > /sys/class/gpio/gpio16/value
		echo 1 > /sys/class/gpio/gpio12/value
		echo 0 > /sys/class/gpio/gpio13/value
	fi
	sleep 10
done
